# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58acf46f28d7c80370abfdab1714a999f323c02bd22f2ebe64b29fedd8e16d88782b19b75d631ebb7be7f90dcf640c8de89874471a00f444d08b96b1b0c8f2b3

test:
  secret_key_base: ddcfe68fd45d7d56487587e08d07f9db9f2c1c9b5b91cabd1499e8a06c72a67cc6b45d827e303bb146a800059ef8eaeb041dd1dba90173c73a380442c732d402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
