# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5e281fa2270f998f2832b86e85fe2ced2d61d9e3bdc68f7d75f354748fe55d8a4396cb27f5938d83fa9c51faf8c92c755a6fb61adb5395641045d7929064a8

test:
  secret_key_base: f3b58f662bbb39aaf3aab8c4c3627ee36a71d785816469d1e14b83b6a8e52c5200d052b3e229ce43ee37579ac277b1196c0b1f7e66033fe8320d138d9c1ff4c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
